import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BUILDINGS, CORE_UPGRADES } from '../data/buildings';
import { colors } from '../constants/theme';
import { Building, BuildingType, CoreCarState, GameState } from '../types/game';
const cost=(c:Record<string,number|undefined>)=>Object.entries(c).map(([k,v])=>`${v} ${k.toUpperCase()}`).join('  ·  ');
export type Selection={kind:'building';building:Building}|{kind:'core';core:CoreCarState}|{kind:'slot';id:string}|null;
export function ActionSheet({selection,state,onClose,onBuild,onUpgrade,onCore}:{selection:Selection;state:GameState;onClose:()=>void;onBuild:(id:string,t:BuildingType)=>void;onUpgrade:(id:string)=>void;onCore:()=>void}){if(!selection)return null;return <Modal transparent animationType="slide" visible onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><View style={s.handle}/><Pressable onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable>{selection.kind==='slot'?<BuildPanel state={state} slot={selection.id} build={(t)=>{onBuild(selection.id,t);onClose()}}/>:selection.kind==='core'?<CorePanel state={state} onCore={onCore}/>:<BuildingPanel building={selection.building} core={state.core} upgrade={onUpgrade}/>}</View></Modal>}
function BuildPanel({state,slot,build}:{state:GameState;slot:string;build:(t:BuildingType)=>void}){return <><Title>CONSTRUIR</Title><Text style={s.sub}>Choose a structure for this build site.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(Object.keys(BUILDINGS) as BuildingType[]).map(t=>{const d=BUILDINGS[t];const exists=d.unique&&state.buildings.some(b=>b.type===t);return <Pressable key={t} disabled={exists} onPress={()=>build(t)} style={[s.card,exists&&s.disabled]}><Text style={s.cardIcon}>{d.icon}</Text><Text style={s.cardName}>{d.name}</Text><Text style={s.cost}>{cost(d.costs[0])}</Text><Text style={s.time}>⏱ {d.constructionTime/1000}s</Text>{exists&&<Text style={s.lock}>UNIQUE · OWNED</Text>}</Pressable>})}</ScrollView></>}
function BuildingPanel({building,core,upgrade}:{building:Building;core:CoreCarState;upgrade:(id:string)=>void}){const d=BUILDINGS[building.type],next=d.production?.perMinute[building.level],current=d.production?(d.production.perMinute[building.level-1]??0):undefined,locked=building.level>=core.level;return <><Title>{d.name} — LV.{building.level}</Title><Text style={s.sub}>{d.description}</Text>{current!==undefined&&<View style={s.stats}><Text style={s.stat}>PRODUCTION  {current} {d.production?.resource.toUpperCase()}/MIN</Text>{next!==undefined&&<Text style={s.next}>NEXT  {next}/MIN</Text>}</View>}{building.status!=='ready'?<Timer endsAt={building.timer?.endsAt}/>:building.level>=3?<Text style={s.max}>MAXIMUM LEVEL</Text>:<><Text style={s.require}>REQUIREMENTS · {cost(d.costs[building.level]??{})}</Text><Text style={s.require}>TIME · {d.upgradeTime/1000}s</Text>{locked&&<Text style={s.lock}>Requer Core Lv.{building.level+1}</Text>}<Button label="UPGRADE" disabled={locked} onPress={()=>upgrade(building.id)}/></>}</>}
function CorePanel({state,onCore}:{state:GameState;onCore:()=>void}){const level=state.core.level;if(level>=3)return <><Title>CORE — LV.3</Title><Text style={s.max}>MAXIMUM CORE · CITY LIMIT UNLOCKED</Text></>;const target=(level+1) as 2|3,u=CORE_UPGRADES[target];return <><Title>CORE — LV.{level}</Title><Text style={s.neon}>{u.name}</Text><Text style={s.require}>REQUIRES · GARAGE LV.{u.garageLevel}</Text><Text style={s.require}>{cost(u.cost)}</Text><Text style={s.require}>TIME · 15s</Text><Text style={s.unlock}>UNLOCKS BUILDINGS LV.{target}</Text>{state.core.timer?<Timer endsAt={state.core.timer.endsAt}/>:<Button label="UPGRADE CORE" onPress={onCore}/>}</>}
function Timer({endsAt}:{endsAt?:number}){return <View style={s.timerBox}><Text style={s.timerText}>WORK IN PROGRESS · {Math.max(0,Math.ceil(((endsAt??0)-Date.now())/1000))}s</Text><View style={s.progress}/></View>}
function Title({children}:{children:React.ReactNode}){return <Text style={s.title}>{children}</Text>};function Button({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'#0008'},sheet:{position:'absolute',bottom:0,left:0,right:0,minHeight:310,maxHeight:'56%',backgroundColor:colors.panel,borderTopWidth:3,borderTopColor:colors.orange,padding:20,paddingBottom:30},handle:{width:50,height:4,borderRadius:2,backgroundColor:'#60666b',alignSelf:'center',marginBottom:12},close:{position:'absolute',right:15,top:10,padding:8},closeText:{fontSize:28,color:colors.muted},title:{fontSize:21,fontWeight:'900',color:colors.text,letterSpacing:1},sub:{color:colors.muted,marginTop:5,marginBottom:13},card:{width:150,height:155,backgroundColor:'#252a2e',borderWidth:2,borderColor:'#51575c',marginRight:10,padding:12,alignItems:'center'},cardIcon:{fontSize:35},cardName:{color:colors.text,fontWeight:'900',fontSize:12,marginTop:6},cost:{color:colors.yellow,fontSize:9,marginTop:8,textAlign:'center'},time:{color:colors.cyan,fontSize:10,marginTop:6},disabled:{opacity:.35},lock:{color:colors.red,fontWeight:'900',fontSize:11,marginTop:10},stats:{backgroundColor:'#22272b',padding:12,borderLeftWidth:3,borderLeftColor:colors.cyan},stat:{color:colors.text,fontWeight:'800'},next:{color:colors.green,marginTop:5,fontWeight:'800'},require:{color:colors.muted,fontWeight:'700',marginTop:10},neon:{color:colors.cyan,fontWeight:'900',fontSize:17,marginTop:12},unlock:{color:colors.yellow,fontWeight:'900',marginTop:15},button:{height:48,backgroundColor:colors.orange,alignItems:'center',justifyContent:'center',marginTop:18,borderBottomWidth:4,borderBottomColor:'#9a3c08'},buttonText:{color:'#130b05',fontWeight:'900',letterSpacing:1},max:{color:colors.yellow,fontSize:16,fontWeight:'900',marginTop:30},timerBox:{height:60,backgroundColor:'#202b2d',marginTop:20,padding:12,overflow:'hidden'},timerText:{color:colors.cyan,fontWeight:'900'},progress:{position:'absolute',left:0,bottom:0,width:'65%',height:5,backgroundColor:colors.cyan}});
