import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Dimensions, PanResponder, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { colors, WORLD } from '../constants/theme';
import { QUESTS } from '../data/quests';
import { powerOf } from '../systems/economy';
import { useGame } from '../game/GameProvider';
import { ActionSheet, Selection } from './ActionSheet';
import { BuildingView, ConstructionSlot } from './BuildingView';
import { CoreCarVisual } from './CoreCarVisual';
import { BottomHud, QuestBar, TopHud } from './Hud';
import { DebugPanel } from './DebugPanel';

const {width:SCREEN_W,height:SCREEN_H}=Dimensions.get('window');
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function GameScreen(){const game=useGame();const [selection,setSelection]=useState<Selection>(null),[tab,setTab]=useState('CITY'),[debug,setDebug]=useState(false),[splash,setSplash]=useState(true);const pan=useRef(new Animated.ValueXY({x:SCREEN_W/2-WORLD.width/2,y:SCREEN_H/2-WORLD.height/2})).current;const origin=useRef({x:0,y:0});
 useEffect(()=>{const t=setTimeout(()=>setSplash(false),1200);return()=>clearTimeout(t)},[]);
 const responder=useMemo(()=>PanResponder.create({onStartShouldSetPanResponder:()=>false,onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>5||Math.abs(g.dy)>5,onPanResponderGrant:()=>{pan.stopAnimation(v=>origin.current=v)},onPanResponderMove:(_,g)=>pan.setValue({x:clamp(origin.current.x+g.dx,SCREEN_W-WORLD.width,0),y:clamp(origin.current.y+g.dy,SCREEN_H-150-WORLD.height,80)}),onPanResponderRelease:()=>{}}),[pan]);
 if(!game.ready)return <View style={s.loading}><ActivityIndicator color={colors.orange}/></View>;
 if(splash)return <View style={s.splash}><Text style={s.logo}>UNDERGROUND</Text><Text style={s.tag}>BUILD BELOW · RISE ABOVE</Text></View>;
 const quest=QUESTS[game.state.questIndex]?.title??'All pilot objectives complete';
 return <SafeAreaView style={s.root}><View style={s.viewport} {...responder.panHandlers}>{tab==='CITY'?<Animated.View style={[s.world,{transform:pan.getTranslateTransform()}]}><WorldDecor/>
   <Pressable style={[s.entity,{left:410,top:375}]} onPress={()=>setSelection({kind:'core',core:game.state.core})}><CoreCarVisual level={game.state.core.level}/>{game.state.core.timer&&<Text style={s.coreTimer}>UPGRADING · {Math.ceil((game.state.core.timer.endsAt-Date.now())/1000)}s</Text>}</Pressable>
   {game.state.buildings.map(b=><View key={b.id} style={[s.entity,{left:b.position.x,top:b.position.y}]}><BuildingView building={b} onPress={()=>setSelection({kind:'building',building:b})}/></View>)}
   {game.state.slots.map(slot=><View key={slot.id} style={[s.entity,{left:slot.position.x,top:slot.position.y}]}><ConstructionSlot onPress={()=>setSelection({kind:'slot',id:slot.id})}/></View>)}<NPC x={360} y={280} delay={0}/><NPC x={610} y={590} delay={800}/><NPC x={760} y={180} delay={1500}/></Animated.View>:<View style={s.coming}><Text style={s.comingIcon}>⚠</Text><Text style={s.comingTitle}>{tab}</Text><Text style={s.comingText}>COMING SOON</Text></View>}</View>
 <TopHud resources={game.state.resources} power={powerOf(game.state)} onDebug={()=>__DEV__&&setDebug(true)}/><QuestBar title={quest}/><BottomHud active={tab} onSelect={setTab}/>{game.message&&<View style={s.toast}><Text style={s.toastText}>{game.message}</Text></View>}
 <ActionSheet selection={selection} state={game.state} onClose={()=>setSelection(null)} onBuild={game.build} onUpgrade={game.upgradeBuilding} onCore={game.upgradeCore}/>{__DEV__&&<DebugPanel visible={debug} onClose={()=>setDebug(false)}/>}</SafeAreaView>}
function WorldDecor(){return <><View style={s.roadH}/><View style={s.roadV}/>{[...Array(18)].map((_,i)=><View key={i} style={[s.crack,{left:(i*173)%1000,top:(i*117)%850,transform:[{rotate:`${i*23}deg`}]}]}/>) }<Text style={[s.graffiti,{left:70,top:115}]}>NO RULES</Text><Text style={[s.graffiti,{right:45,bottom:80,color:colors.cyan}]}>// U.G.</Text><View style={s.fence}/></>}
function NPC({x,y,delay}:{x:number;y:number;delay:number}){const move=useRef(new Animated.Value(0)).current;useEffect(()=>{const anim=Animated.loop(Animated.sequence([Animated.delay(delay),Animated.timing(move,{toValue:35,duration:2400,useNativeDriver:true}),Animated.timing(move,{toValue:0,duration:2400,useNativeDriver:true})]));anim.start();return()=>anim.stop()},[move,delay]);return <Animated.View style={[s.npc,{left:x,top:y,transform:[{translateX:move}]}]}><View style={s.head}/><View style={s.body}/></Animated.View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},loading:{flex:1,backgroundColor:colors.bg,alignItems:'center',justifyContent:'center'},splash:{flex:1,backgroundColor:'#080a0c',alignItems:'center',justifyContent:'center'},logo:{fontSize:36,fontWeight:'900',letterSpacing:5,color:colors.orange,textShadowColor:'#ff5b18',textShadowRadius:18},tag:{color:colors.muted,fontSize:10,fontWeight:'800',letterSpacing:3,marginTop:10},viewport:{flex:1,overflow:'hidden'},world:{position:'absolute',width:WORLD.width,height:WORLD.height,backgroundColor:colors.asphalt,borderWidth:8,borderColor:'#2c3135'},roadH:{position:'absolute',top:410,left:0,right:0,height:150,backgroundColor:'#111416',borderTopWidth:2,borderBottomWidth:2,borderColor:'#33383c'},roadV:{position:'absolute',left:465,top:0,bottom:0,width:130,backgroundColor:'#111416',borderLeftWidth:2,borderRightWidth:2,borderColor:'#33383c'},crack:{position:'absolute',width:38,height:2,backgroundColor:'#282d30'},graffiti:{position:'absolute',fontSize:27,fontWeight:'900',fontStyle:'italic',color:colors.red,transform:[{rotate:'-8deg'}],opacity:.65},fence:{position:'absolute',top:35,left:40,right:40,height:8,backgroundColor:'#454a4e',borderStyle:'dashed',borderWidth:2,borderColor:'#777'},entity:{position:'absolute',zIndex:2},coreTimer:{color:colors.cyan,textAlign:'center',fontWeight:'900',fontSize:10,marginTop:4},npc:{position:'absolute',width:20,height:40,zIndex:1,alignItems:'center'},head:{width:11,height:11,borderRadius:6,backgroundColor:'#d8aa83'},body:{width:14,height:24,backgroundColor:colors.yellow,borderRadius:4},coming:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#111418'},comingIcon:{fontSize:50,color:colors.orange},comingTitle:{color:colors.text,fontSize:30,fontWeight:'900',letterSpacing:4},comingText:{color:colors.muted,fontWeight:'800',letterSpacing:3,marginTop:10},toast:{position:'absolute',zIndex:50,top:105,alignSelf:'center',backgroundColor:'#111e1e',borderWidth:2,borderColor:colors.cyan,paddingVertical:10,paddingHorizontal:20},toastText:{color:colors.cyan,fontWeight:'900'},});
