import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '../constants/theme';
import { Resources } from '../types/game';
const n=(v:number)=>Math.floor(v).toLocaleString();
export function TopHud({resources,power,onDebug}:{resources:Resources;power:number;onDebug:()=>void}){return <View style={s.top}><Pressable onLongPress={onDebug} style={s.profile}><View style={s.avatar}><Text>😎</Text></View><View><Text style={s.level}>LV. 1</Text><Text style={s.power}>⚡ {n(power)}</Text></View></Pressable><View style={s.resources}><Resource icon="⚙" value={n(resources.scrap)}/><Resource icon="◆" value={n(resources.fuel)}/><Resource icon="$" value={n(resources.cash)}/></View></View>}
function Resource({icon,value}:{icon:string;value:string}){return <View style={s.resource}><Text style={s.resourceIcon}>{icon}</Text><Text style={s.resourceValue}>{value}</Text></View>}
export function QuestBar({title}:{title:string}){return <View style={s.quest}><Text style={s.questTag}>OBJECTIVE</Text><Text style={s.questText}>{title}</Text><Text style={s.arrow}>›</Text></View>}
const tabs=['CITY','CREW','FIGHTERS','BAG','WORLD'];
export function BottomHud({active,onSelect}:{active:string;onSelect:(t:string)=>void}){return <View style={s.bottom}>{tabs.map((t,i)=><Pressable key={t} onPress={()=>onSelect(t)} style={[s.tab,active===t&&s.tabActive]}><Text style={s.tabIcon}>{['⌂','♟','✊','▣','◎'][i]}</Text><Text style={[s.tabText,active===t&&{color:colors.orange}]}>{t}</Text></Pressable>)}</View>}
const s=StyleSheet.create({top:{position:'absolute',top:0,left:0,right:0,height:88,zIndex:20,backgroundColor:'#0b0e11ee',borderBottomWidth:2,borderBottomColor:colors.orange,flexDirection:'row',alignItems:'flex-end',paddingHorizontal:10,paddingBottom:9},profile:{width:105,flexDirection:'row',alignItems:'center'},avatar:{width:38,height:38,borderRadius:19,borderWidth:2,borderColor:colors.orange,backgroundColor:'#333',alignItems:'center',justifyContent:'center',marginRight:6},level:{color:colors.text,fontSize:10,fontWeight:'900'},power:{color:colors.yellow,fontSize:11,fontWeight:'900'},resources:{flex:1,flexDirection:'row',justifyContent:'space-around'},resource:{minWidth:65,height:31,borderRadius:15,backgroundColor:'#272b2f',borderWidth:1,borderColor:'#4d5358',flexDirection:'row',alignItems:'center',paddingHorizontal:7},resourceIcon:{color:colors.orange,fontWeight:'900',marginRight:4},resourceValue:{color:colors.text,fontSize:11,fontWeight:'800'},quest:{position:'absolute',bottom:72,left:8,right:8,height:45,zIndex:20,backgroundColor:'#171b20f5',borderLeftWidth:4,borderLeftColor:colors.yellow,flexDirection:'row',alignItems:'center',paddingHorizontal:10},questTag:{color:colors.yellow,fontSize:8,fontWeight:'900',marginRight:8},questText:{color:colors.text,fontWeight:'800',flex:1},arrow:{color:colors.orange,fontSize:26},bottom:{position:'absolute',bottom:0,left:0,right:0,height:72,zIndex:20,backgroundColor:'#0b0d10',borderTopWidth:2,borderTopColor:'#454a4f',flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:'#241b14',borderTopWidth:3,borderTopColor:colors.orange},tabIcon:{fontSize:21,color:colors.text},tabText:{fontSize:8,color:colors.muted,fontWeight:'900',marginTop:3}});
