import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors } from '../constants/theme';
import { ResourceKey, Resources } from '../types/game';
const n=(v:number)=>Math.floor(v).toLocaleString();
const resourceMeta:Record<ResourceKey,{icon:string;color:string}>={wood:{icon:'▰',color:'#d99a45'},iron:{icon:'⬡',color:'#9bb6bd'},water:{icon:'●',color:'#37bce8'},food:{icon:'◆',color:'#75c96b'},diamond:{icon:'♦',color:'#63e5ef'}};
export function TopHud({resources,power,onDebug}:{resources:Resources;power:number;onDebug:()=>void}){return <View style={s.top}><View style={s.row}><Pressable onLongPress={onDebug} style={s.profile}><View style={s.avatar}><Text>😎</Text></View><View><Text style={s.level}>LV. 1</Text><Text style={s.power}>⚡ {n(power)}</Text></View></Pressable><View style={s.brand}><Text style={s.brandText}>UNDERGROUND</Text><Text style={s.district}>THE YARD</Text></View></View><View style={s.resources}>{(Object.keys(resourceMeta) as ResourceKey[]).map(k=><Resource key={k} icon={resourceMeta[k].icon} color={resourceMeta[k].color} label={k} value={n(resources[k])}/>)}</View></View>}
function Resource({icon,color,label,value}:{icon:string;color:string;label:string;value:string}){return <View style={s.resource}><Text style={[s.resourceIcon,{color}]}>{icon}</Text><View><Text style={s.resourceLabel}>{label.toUpperCase()}</Text><Text numberOfLines={1} adjustsFontSizeToFit style={s.resourceValue}>{value}</Text></View></View>}
export function QuestBar({title}:{title:string}){return <View style={s.quest}><Text style={s.questTag}>MISSÃO</Text><Text style={s.questText}>{title}</Text><Text style={s.arrow}>›</Text></View>}
const tabs=['CITY','CREW','FIGHTERS','BAG','WORLD'];
export function BottomHud({active,onSelect}:{active:string;onSelect:(t:string)=>void}){return <View style={s.bottom}>{tabs.map((t,i)=><Pressable key={t} onPress={()=>onSelect(t)} style={[s.tab,active===t&&s.tabActive]}><Text style={s.tabIcon}>{['⌂','♟','✊','▣','◎'][i]}</Text><Text style={[s.tabText,active===t&&{color:colors.orange}]}>{t}</Text></Pressable>)}</View>}
const s=StyleSheet.create({top:{position:'absolute',top:0,left:0,right:0,height:116,zIndex:20,backgroundColor:'#0b0e11f5',borderBottomWidth:2,borderBottomColor:colors.orange,paddingHorizontal:8,paddingBottom:7,paddingTop:7},row:{height:51,flexDirection:'row',alignItems:'center'},profile:{width:104,flexDirection:'row',alignItems:'center'},avatar:{width:36,height:36,borderRadius:18,borderWidth:2,borderColor:colors.orange,backgroundColor:'#333',alignItems:'center',justifyContent:'center',marginRight:6},level:{color:colors.text,fontSize:9,fontWeight:'900'},power:{color:colors.yellow,fontSize:10,fontWeight:'900'},brand:{flex:1,alignItems:'flex-end'},brandText:{color:colors.orange,fontSize:13,fontWeight:'900',letterSpacing:2},district:{color:colors.muted,fontSize:8,fontWeight:'800',letterSpacing:3},resources:{height:48,flexDirection:'row',gap:4},resource:{flex:1,minWidth:0,borderRadius:5,backgroundColor:'#252a2e',borderWidth:1,borderColor:'#454c51',flexDirection:'row',alignItems:'center',justifyContent:'center',paddingHorizontal:3},resourceIcon:{fontSize:12,fontWeight:'900',marginRight:3},resourceLabel:{color:colors.muted,fontSize:6,fontWeight:'900'},resourceValue:{color:colors.text,fontSize:10,fontWeight:'900',maxWidth:48},quest:{position:'absolute',bottom:72,left:8,right:8,height:45,zIndex:20,backgroundColor:'#171b20f5',borderLeftWidth:4,borderLeftColor:colors.yellow,flexDirection:'row',alignItems:'center',paddingHorizontal:10},questTag:{color:colors.yellow,fontSize:8,fontWeight:'900',marginRight:8},questText:{color:colors.text,fontWeight:'800',flex:1},arrow:{color:colors.orange,fontSize:26},bottom:{position:'absolute',bottom:0,left:0,right:0,height:72,zIndex:20,backgroundColor:'#0b0d10',borderTopWidth:2,borderTopColor:'#454a4f',flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:'#241b14',borderTopWidth:3,borderTopColor:colors.orange},tabIcon:{fontSize:21,color:colors.text},tabText:{fontSize:8,color:colors.muted,fontWeight:'900',marginTop:3}});
